run:
        dataset: topmed # e.g. gnomad, topmed
        hg_version: hg19
        variants_table_dir: topmed-high_confidence-filtered_variant_tables-SNV_only-FILTERED # filtered variant tables (based on population, variant filters and even high-conf-regions)
        win_len: 3000    # e.g. 500, 3000 (window length in nt)
        variant_filter: snv # type of variants to use: snv for SNVs, indels for INDELs, anything else (e.g. all) includes all
        MAF_thres: 0.001  # e.g. 0.0001 (Minor Allele Frequency) 
        population: all    # e.g. all (default), FIN, etc.
        filter_zero_variants_wins: 0        # [deprecated] exclude windows with zero variants from CDF and density plots'
        filter_ccds_variants: False     # default: False (use True to exclude CCDS variants affecting gwRVIS calculation)
        run_identifier: factory-ClinVar_pathogenic-denovodb_benign  # output_dir suffix, e.g. -gnomad-sufficient-coverage-min_depth20-FILTERED_variants 
        Y_label: clinvar_annot
        pathogenic_set: ncER-gwas_catalog-clean
        benign_set: denovodb
fixed:
        kmer: 7          # mutability rate based on k-mer: 7 or 3
        genomic_classes: static_files/genomic_classes.log
        all_variants_upper_thres: -1 # set to '-1' to use default value: (win_len) or set to e.g. 150 (filter_outliers_before_regression-dependent) 
        filter_plot_outliers: True        # e.g. True - affects only plotting of gwRVIS values per genomic class
        z_thres: 3.5    # used when 'filter_plot_outliers' is set to True
        fixed_win_len_for_all_genomic_elements: False  # If False (default value) different classes (but non-overlapping regions) may share the same gwRVIS value if they belong to different parts of the same window - Else for True: every 3kb window will be assigned to a single genomic class element (Not ideal: removes lots of interesting signal)
        min_overlap_ratio: 0.01 # default: 1E-9 (1bp min. overlap) 
